### ISSUE TITLE
Played Segments - Needs Testing / Review

### ISSUE THREAD

**Issue by jhaag75** [jhaag75/xapi-videojs#10] opened 2017-07-11 23:11 UTC
Added tracking for the "played-segments" extension (formerly called heat-maps) as this commit https://github.com/jhaag75/xapi-videojs/commit/3fcdedc1681fbffdd46aedf931c3093f1dc5c39c

Please test & review and let me know if this is what we want or if changes need to be made. There's a few key things to look at: 

1. we are currently sending played segments with the played and paused events/verbs. The profile says to send it with the seeked verb, but that doesn't seem to make sense. The seeked verb is sent with time-to and time-from time ranges. We may need to update the description based on how we really want to use this data and what is possible. But that's why we created this demo/prototype :-)

2. The description of played-segments / heat-map is "Heat map data showing parts of the video the actor watched during current registration in chronological order (e.g., 0.000[.]12.000[,]14.000[.]21.000[,]18.000[.]30.000). String Value. Each part of the video watched is separated with [,]. The 'Time From' and 'Time To' values are separated with [.]. The time values must match the values recorded as time, time-to and time-from in played, paused, seeked statements. 

3. the video profile recommends putting the segments into this format "0.000[.]9.207[,]13.079[.]16.222" but that would require quite a bit of manipulation to the data returned from the TimeRange object in videoJS. So, for now it is showing the data like this:

  "result": {
    "extensions": {
      "https://w3id.org/xapi/video/extensions/played-segments": [
        "0.000[.]9.207",
        "13.079[.]16.222"
      ],

**Comment by jhaag75** [comment] 2017-07-12 01:57
Also, that description from 2. (above) says "during current registration" but what does that mean. I don't recall using the concept of registration for the video profile. We are requiring a session-id though. Is that what we meant here? To say "session" not "registration"??? Please clarify.

**Comment by liveaspankaj** [comment] 2017-07-12 09:20
We had few discussion related to heat map where we talked about registration. 

It is a core concept of Experience API and has a dedicated parameter for registration in Statements API as well as State and other APIs. 


Pankaj

**Comment by jhaag75** [comment] 2017-07-12 13:21
Thanks Pankaj. Do we have this documented anywhere? 

So are we just using registration for heat-map / played-segments? What other statements require the use of registration?

**Comment by jhaag75** [comment] 2017-07-12 13:22
Seems inconsistent in how people are using it. I just want to make sure I understand the intent so we can update this prototype appropriately. Here's a recent link / discussion on the topic:

http://datainteroperability.org/2017/04/registering-statements/

**Comment by jhaag75** [comment] 2017-07-13 19:49
See the section "Come up with new extensions" from the link above. We are basically doing that with the session-id extension. Isn't it redundant to store both? I believe only registration can be filtered on from the LRS. So another option is to drop session-id as an extension and just use registration. Appreciate your thoughts on this. I can easily add registration to the statements too, but didn't want to do it unless we have some consensus.

**Comment by jhaag75** [comment] 2017-07-13 20:02
Another question regarding played segments. Shouldn't we also be sending this with completed statements? It doesn't mention it in the description, but thought it probably should.

**Comment by liveaspankaj** [comment] 2017-07-13 22:06
We have some information here but that can be improved:
https://liveaspankaj.gitbooks.io/xapi-video-profile/content/statement_data_model.html

The inconsistencies mentioned about registration value in that article doesn't really cause any major issues as far as I can think of. And, they are probably not going to effect the use of registration as intended by the Experience API.

 To give an example: Lets say an employee needs to take Sexual Harassment video course every year as part of your company requirement. 

When he takes the video for the first time a registration uuid is generated and passed in the url when launching the content, and all statements have that registration value. 

Lets assume he stops after 5 minutes. Comes back after 3 days to complete the video. The new launch after 3 days will have a new session, but will be part of the same registration and he can complete the remaining content to complete the course. 

To be able to mark the video as complete (i.e. send a completed verb), we need to know what he has already completed, and to do that we can fetch the played segments information from the past attempt with the same registration. 

Now, when the employee has to take the course again next year. A new registration is generated and the video is launched with new registration. This will do two things, it will keep related statements together under same registration, but more importantly, it will not mix the "played-segements" from last year's attempts. 

If we do not use registration, fetching the played segments will get the data from last year, and mark the course as completed almost as soon as it starts. 

Let me know if that makes sense. 

Regarding what statements should have "played-segments". I believe it can be on paused, seeked, and completed. In the gitbook I have mentioned that it MUST be on paused and completed. But for seeked also it can be added, if there is confusion we can may be add it for paused and completed first.

**Comment by jmkevan** [comment] 2017-07-14 02:22
@Jason -Thanks for sharing the DISC post from Aaron. I actually think we 
are doing the 'natural punctuation' that Aaron's talking about using 
registration for the video profile. We have an initialized and completed 
statement as our predefined beginning and end. Registration then is our 
collection of all statements related to a single 'punctuated' video 
experience. Maybe we can ask Aaron if that meets his litmus test or 
speaks to the granularity he is targeting, but he appears to be asking 
for suggestions on this anyway.

While Pankaj's example is a good instance where registration to separate 
instances of these punctuated experiences makes sense... we could live 
without it. It's likely, at least in the example provided, that any 
follow-up instruction on Sexual Harassment would either be a different 
video or could be classified as a different 'activity'. Indeed I would 
argue it should be a different activity from any learning science 
perspective. In which case we could search the LRS for the agent, 
activity and object to get the statements we seek. I think that's what 
Aaron refers to when he says that the registration in this instance 
would 'add no information'.

So even if we are using registration as a natural punctuation for video 
interactions, I am not sure natural punctuation makes sense. Of course, 
it doesn't appear Aaron was suggesting that.

As I think about it... it seems impractical to use a registration ID to 
access video statements from a year before. You would likely need to 
store a list of registration UUIDs somewhere or send an additional 
statement somewhere with this array of registrations in order for that 
to make sense. You are much more likely to search for the agent, 
activity and date ranges you are looking for. Yes, that's more 
variables, but also more readily available than a random registration. I 
supposed you could grab the session-id from a statement in that range 
and use it to find the registration ids associated to it, but that seems 
like a mess.

It appears the heatmap extension is mentioned under the 'usage' section 
of the completed verb. So I think you are correct that we should send 
the played segments with it.

I think we were only sending played segments with 'paused' and not 
'played'. I suppose you could send the 'time from' with played, but I am 
not sure that's really worth it. Without the second pairing of data, you 
would likely throw away that data point anyway as there is no way to 
determine where 'time to' would have occurred.  I haven't looked at your 
implementation yet though, so I should do that first before commenting 
more.

- Jon

Jonathan Kevan
R&D Coordinator, Distance Course Design & Consulting (DCDC)
College of Education, University of Hawai‘i at Manoa
1776 University Avenue, Wist 245, Honolulu, Hawai‘i 96822
Web: dcdc.coe.hawaii.edu




------ Original Message ------

**Comment by jmkevan** [comment] 2017-07-14 02:32
I am not sure I described the issue with Pankaj's example clearly 
enough.

We wouldn't need session-id to differentiate (in this example) between 
the original and subsequent Sexual Harassment training if the 'activity' 
was different, which IMO it should be.
We wouldn't need the registration either unless we were trying to track 
and compare user actions across very specific interactions. So I guess 
the question is, what situation would we need to differentiate between 
video experiences that could not be searched using the actor, verb or 
object. The 'heatmap' concept is fine with the aggregate data which can 
be harvested without the registration ID from the completed verbs.

- J

Jonathan Kevan
R&D Coordinator, Distance Course Design & Consulting (DCDC)
College of Education, University of Hawai‘i at Manoa
1776 University Avenue, Wist 245, Honolulu, Hawai‘i 96822
Web: dcdc.coe.hawaii.edu




------ Original Message ------
From: "Jonathan Kevan" <jkevan@hawaii.edu>
To: "jhaag75/xapi-videojs" 
<reply@reply.github.com>; 
"jhaag75/xapi-videojs" <xapi-videojs@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Sent: 7/13/2017 4:22:19 PM
Subject: Re[2]: [jhaag75/xapi-videojs] Played Segments - Needs Testing / 
Review (#10)

**Comment by jmkevan** [comment] 2017-07-14 03:26
Code looks great Jason. I don't see any immediate issues.

That's a nice little feature you found in videoJS to get the timeRange 
object. This library has quite the treasure trove of methods if you can 
dig 'em out. On a side note, here is an example of using the timeRange 
to create a 1 time heat map:
https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/buffering_seeking_time_ranges

The implementation appears similar to what Pankaj had original proposed. 
I am going to see if I can replicate it in d3.

- J

Jonathan Kevan
R&D Coordinator, Distance Course Design & Consulting (DCDC)
College of Education, University of Hawai‘i at Manoa
1776 University Avenue, Wist 245, Honolulu, Hawai‘i 96822
Web: dcdc.coe.hawaii.edu




------ Original Message ------
From: "Jonathan Kevan" <jkevan@hawaii.edu>
To: "jhaag75/xapi-videojs" 
<reply@reply.github.com>; 
"jhaag75/xapi-videojs" <xapi-videojs@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Sent: 7/13/2017 4:32:35 PM
Subject: Re[3]: [jhaag75/xapi-videojs] Played Segments - Needs Testing / 
Review (#10)

**Comment by jhaag75** [comment] 2017-07-14 23:33
I'll work on adding registration. What Pankaj said makes sense to me. Perhaps we can add it and test it against the ADL LRS and Pankaj's LRS to see where the value is for filtering, etc vs. just using session-id. Thanks guys!

**Comment by liveaspankaj** [comment] 2017-08-05 23:38
I have added/committed a one line fix to the formating of played segments. 

I have few observations:
1. "played-segments" is redundant in "played" verb. so we can/should remove it from there. 
2. "progress" value is currently calculated based on the position in slider. we need to change it to be based on "played-segments" 
3. "completed" statement need to be based on "progress" 
4. "played-segments" doesn't send value exactly as in "played" and "paused" time extensions. it exclude plause/play that happens without skipping much space. we should probably use the values as per the statements sent. https://screencast.com/t/6Kmdfz0Je 
or we need to change the video profile documentation.

**Comment by liveaspankaj** [comment] 2017-08-07 21:58
We had following related decisions in todays meeting, leaving the issue open till these are done:

1. Completed and Progress: The current completed and progress is using the position in video for progress and completed. As per the profile we need to calculate the actual consumption of the video. Pankaj to take care of the related code.

2. Played Segments calculation: VideoJS has its own time segments which is being used currently for played segments. However, VideoJS is skipping some segments which includes clicking pause/play at very close time frame. This is technically wrong as per the spec. To fix this, Pankaj to modify "played-segments" value in the prototype. Also, Pankaj to take care that these minor time gaps do not hold back completion.

3. Played Segments on played statement: Sending played segments on played verb is not required and doesn't add value, so it was decided that we will remove it from there.

**Comment by liveaspankaj** [comment] 2017-08-21 20:24
Hi @jhaag75 @jmkevan, 

It is not yet complete, but you might like to see this https://screencast.com/t/wfioYEfm
I could not resist the temptation to show it.

So, I have been able to update the played segments calculations. I have also been able to show a heat map in GrassBlade LRS based on the played segments string. 

To Do:
1. Pull the past attempts played segments to be able to get combined played segments and progress.
2. Send completed consuming the entire video. 

(not yet committed the code)

**Comment by jhaag75** [comment] 2017-08-21 20:45
Thanks Pankaj! Submit a new PR when ready. I'm going to get to my tasks as
well this week!

**Comment by jmkevan** [comment] 2017-08-21 20:49
Looks awesome!

Can't wait to start playing with it :-)

Jonathan Kevan
R&D Coordinator, Distance Course Design & Consulting (DCDC)
College of Education, University of Hawai‘i at Manoa
1776 University Avenue, Wist 245, Honolulu, Hawai‘i 96822
Web: dcdc.coe.hawaii.edu


------ Original Message ------

**Comment by liveaspankaj** [comment] 2017-08-21 23:40
Thanks @jmkevan @jhaag75 

I have been able to complete the played segments part along with getting previous played segments. To clarify this is what happens:
1. When video is started (first play event). I pull the last paused statement from the actor for this video. If registration is provided that is also added to the filter. That means, we pull last paused statement for this registration from the actor for this video.

2. Using the last paused statement returned. We initialise the value of played segments from this paused statement. Now, all new segments will be added to it. 
https://screencast.com/t/rt2A5nMn

3. Also from the last paused statement, we get the time value to set the time in video where the video will start. (Resume)

4. The progress % is now automatically calculated based on the new combined played segments. 

5. The progress and played segments will automatically reset when the registration value is changed.


ToDo:
Completed statement to be sent when progress is 1 (100%). 
(Wondering if its a good idea to check for completion while the video is running in the timeupdate event. Probably I should find a intelligent way to not doing calculations on every timeupdate because timeupdate happens multiple times every second.)

Will probably commit it tomorrow. And, will also update the code to a GrassBlade Cloud LRS instance, so you can use it to see the heatmap visualisation.

**Comment by liveaspankaj** [comment] 2017-09-03 17:20
Sorry for the delayed. could not make much progress beyond the last message, so I decided to commit. 

I have created a GrassBlade Cloud LRS instance for Video COP where you can see heatmaps in action:
https://videocop.gblrs.com/
Email: demo@nextsoftwaresolutions.com
Password: demo

You can send statements using these credentials: 
Endpoint: https://videocop.gblrs.com/xAPI/
API User: 13-38e2a3a46ece5e3
API Password: 00ac31678f197b66d4e3ff514

ToDo:
Completed statement to be sent when progress is 1 (100%).
(Wondering if its a good idea to check for completion while the video is running in the timeupdate event. Probably I should find a intelligent way to not doing calculations on every timeupdate because timeupdate happens multiple times every second.)

**Comment by liveaspankaj** [comment] 2017-10-18 23:35
I have done this.
1. Completed statement now sent when all 100% of the video is watched. 
2. Terminated statement is now sent on window/tab close instead of sending it on reaching the end of the video.

**Comment by jhaag75** [comment] 2017-10-18 23:41
Rock. On. Great job Pankaj! Ready to help promote when you guys feel it's
ready. Perhaps your LRS to demo with it would be good too if you have some
screenshots.

**Comment by liveaspankaj** [comment] 2017-10-19 00:29
ok, will try to create a demo page

**Comment by jhaag75** [comment] 2018-01-16 13:33
This played segments seems to work fine. Closing this issue.

**Closed as completed** 2018-03-07 04:31 UTC
